### ISSUE TITLE
Crash on traceClassesMatching(pattern:) xCode 11.4, obj c

### ISSUE THREAD

**Issue by svilon** [johnno1962/SwiftTrace#15]
I'm having a crash When trying to start tracer calling something like:
`SwiftTrace.traceClassesMatching(pattern: "Panel")`
Worked perfectly until xCode 11.4. Base code is in objective-c, with swift code inclusions.

Crashes inside `forAllClasses` method with message:
` *** NSForwarding: warning: object 0x7fff89115000 of class 'PFEmbeddedMulticasterImplementation' does not implement methodSignatureForSelector: -- trouble ahead
 *** NSForwarding: warning: object 0x7fff89115000 of class 'PFEmbeddedMulticasterImplementation' does not implement doesNotRecognizeSelector: -- abort`

I've found that probably return type of `objc_copyClassList` has changed and 've found solution for myself here: https://stackoverflow.com/questions/60853427/objc-copyclasslist-crash-exc-bad-instruction-after-update-to-ios-13-4-xcode-1

Therefore I've overridden 'forAllClasses' method with following implementation:
```
    override open class func forAllClasses( callback: (_ aClass: AnyClass,
                    _ stop: inout Bool) -> Void ) -> Bool {
        var stopped = false
        var nc: UInt32 = 0

        if let classesPointer = objc_copyClassList(&nc) {
            let classes = UnsafeBufferPointer(start: classesPointer, count: Int(nc))
            for aClass in (0..<Int(nc)).map({ classes[$0] }) {
                callback(aClass, &stopped)
                if stopped {
                    break
                }
            }
            free(UnsafeMutableRawPointer(classesPointer))
        }

        return stopped
    }
```

Please review, maybe there is something you should fix in the tracer's code.
Thanks a lot for all the job you've done so far!

**Comment by johnno1962** [comment]
Hmmm, looks like we’ll have to get a new release out. I noticed this recently and raised a PR on the Stdlib: https://github.com/apple/swift/pull/31128. There's a simple workaround like you say but it will take time while a real solution gets through to the toolchain. If you update your SwiftTrace pod I’ve added a new 6.0.0 tag and you should be fine.

**Comment by johnno1962** [comment]
With a certain amount of difficulty, I’ve pushed the 6.0.0 tag to CocoaPods.

**Comment by johnno1962** [comment]
version 6.3.2 pushed to cocoa pods. You can now also use it as a Swift Package.
