### ISSUE TITLE
assembler directive is a better choice.

### ISSUE THREAD

**Issue by jmpews** [johnno1962/SwiftTrace#22]
https://github.com/johnno1962/SwiftTrace/blob/master/SwiftTraceGuts/xt_forwarding_trampoline_arm64.s#L93

https://github.com/jmpews/Dobby/blob/master/source/TrampolineKit/ClosureTrampolineBridge/arm64/dummy/dynamic-closure-trampoline-template-arm64.S#L20

**Comment by johnno1962** [comment]
Interesting, How do you mean? -- OK, I see now.. Thanks!
