### ISSUE TITLE
Crash in SwiftArgs.handleArg

### ISSUE THREAD

**Issue by iCodeWoods** [johnno1962/SwiftTrace#38]
All I did was add `SwiftTrace.traceBundle(containing: type(of: self))` to the first line of didFinishLaunchingWithOptions

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/30431268/164194086-24ccfd64-a719-47f3-b7e8-071c7f691645.png">

**Comment by johnno1962** [comment]
Hi, difficult to say exactly what the problem would be without TeamViewing but this is generally to do with a "resilient" type which is passed by reference. What is the signature of the ruction being traced? You can find this by working your way up the stack to the function `swiftDecorate` and printing what is passed in. It is trying to describe the return type.

**Comment by arietis** [comment]
It might be related to Firebase swizzling, I have the same crash now.
Update: I have just tested it with the `FirebaseApp.configure()` commented out and it works fine.

**Comment by johnno1962** [comment]
If anybody is interested I have some time to look at this now (TeamView/Zoom) and have been working on SwiftTrace of late. There is a bit of a mystery with the image uploaded in that the code it trapped on is not the original SwiftTrace code (Type.self == AnyObject?.self makes no sense). Also working with `Firebase` might be a big ask but I can look at it.
