### ISSUE TITLE
Crashing Out on First Usage - Basic configuration demo?

### ISSUE THREAD

**Issue by tikimcfee** [johnno1962/SwiftTrace#39]
Hey again! Saw a ton of work on this and wanted to try it out again. For whatever reason, I can't get back to the original working implementation. Now, all I do is something like `SwiftTrace.traceInstances(ofClass: CodeGrid.self)`, but as soon as SwiftTrace gets the call, it ends up spitting out thousands of `Exclude...` print statements for... what seems like pretty much everything in all SDKs everywhere, heh. There's a snippet below where it's pulling in the SiriOntology, et al! Just looking to see what I can / should do to get every I dotted and T crossed to use this fantastic tool.

EDIT:
It looks like I'm seeing something different when using `SwiftTrace.trace(aClass: CodeGrid.self)` instead of `SwiftTrace.traceInstances(ofClass: CodeGrid.self)`. I'm not getting the world traced which is good, but it looks like not everything is tracing out - functions in extensions in this case. I'd expect there to be lots of function calls between the exclusions and the logging of the two nodes being updated. Seems like I'm just not configuring stuff right, and have a tricky object hierarchy to boot.

EDIT 2:
Might be better if I explain what I'm expecting to happen, or trying to do. I've got this class, `CodeGrid`, with a few extensions and lots of little formatting / IO stuff. I'd like to trace all of the ins and outs of this class being interacted with - even if just an instance - because I'd like to see a really basic 'running trace' of what the order of certain calls is, how often they're called, etc. I'd like to further get that into a list of some kind in-memory so I can iterate over the output and do some analysis on it. However, as mentioned, I'm just hitting little blocks here and there in understanding how this works and how to _properly_ use it. I'd love to expand further if it helps, or work to produce some samples that you can reproduce with!

```
Excluding SwiftTrace of LookAtThat_AppKit.CodeGrid.id.getter : Swift.String
Excluding SwiftTrace of LookAtThat_AppKit.CodeGrid.rootContainerNodeName.getter : Swift.String
Excluding SwiftTrace of LookAtThat_AppKit.CodeGrid.glyphNodeName.getter : Swift.String
Excluding SwiftTrace of LookAtThat_AppKit.CodeGrid.flattedGlyphNodeName.getter : Swift.String
Excluding SwiftTrace of LookAtThat_AppKit.CodeGrid.backgroundNodeName.getter : Swift.String
Excluding SwiftTrace of LookAtThat_AppKit.CodeGrid.backgroundNodeGeometry.getter : Swift.String
Excluding SwiftTrace of LookAtThat_AppKit.CodeGrid.cloneId.getter : Swift.String
Excluding SwiftTrace of LookAtThat_AppKit.CodeGrid.fileName.getter : Swift.String
Excluding SwiftTrace of LookAtThat_AppKit.CodeGrid.(showingRawGlyphs in _264F3C980A92A6BD3C2F4B4FF84BF4B4).getter : Swift.Bool
Excluding SwiftTrace of LookAtThat_AppKit.CodeGrid.codeGridSemanticInfo.getter : LookAtThat_AppKit.CodeGridSemanticMap
Excluding SwiftTrace of LookAtThat_AppKit.CodeGrid.walkSemantics.getter : Swift.Bool
Excluding SwiftTrace of LookAtThat_AppKit.CodeGrid.displayMode.getter : LookAtThat_AppKit.CodeGrid.DisplayMode
Excluding SwiftTrace of LookAtThat_AppKit.CodeGrid.renderer.getter : LookAtThat_AppKit.CodeGrid.Renderer
Excluding SwiftTrace of LookAtThat_AppKit.CodeGrid.measures.getter : LookAtThat_AppKit.CodeGrid.Measures
Excluding SwiftTrace of LookAtThat_AppKit.CodeGrid.rootNode.getter : __C.SCNNode
Excluding SwiftTrace of LookAtThat_AppKit.CodeGrid.rootContainerNode.getter : __C.SCNNode
Excluding SwiftTrace of LookAtThat_AppKit.CodeGrid.rawGlyphsNode.getter : __C.SCNNode
Excluding SwiftTrace of LookAtThat_AppKit.CodeGrid.flattenedGlyphsNode.getter : Swift.Optional<__C.SCNNode>
Excluding SwiftTrace of LookAtThat_AppKit.CodeGrid.backgroundGeometryNode.getter : __C.SCNNode
Excluding SwiftTrace of LookAtThat_AppKit.CodeGrid.backgroundGeometry.getter : __C.SCNBox
LookAtThat_AppKit.CodeGrid.id.setter : "CodeGrid-A9BF7752-132A-4025-8202-95A02BBBECE4"  828.1ms
LookAtThat_AppKit.CodeGrid.flattenedGlyphsNode.setter : <SCNNode: 0x60000077cb00 'CodeGrid-A9BF7752-132A-4025-8202-95A02BBBECE4-glyphs-flattened' | geometry=<SCNGeometry: 0x600000ac33e0> | no child>  0.2ms
Test Case '-[LookAtThat_AppKitTests.LookAtThat_AppKitCodeGridTests testTracing]' passed (0.906 seconds).
```

[Lots of exclusions using `SwiftTrace.traceInstances(ofClass: CodeGrid.self)](https://gist.github.com/tikimcfee/3bc81f735627ee3422a158b6ced2a59a)

**Comment by johnno1962** [comment]
Hey there, I've tweaked a new branch "expanded-interpose" to filter out these .getter methods and expand the api to allow you to trace a type more generally. The problem with the methods in an extension is they are "directly dispatched" rather than going through the class' vtable which is how the "legacy" SwiftTrace method you're using worked. In order to trace methods in an extension you need to use "interposing" which requires you add the "-Xinker -interposbale" "Other Linker Flags" to your project then you can use the type tracing api which I've expanded to cater for this. In other words you need to do both of the following when you use extensions:
```
        SwiftTrace.typeLookup = true
        SwiftTrace.trace(aClass: C.self)
        _ = SwiftTrace.interpose(aType: C.self)
```
Here's a small example project:
[STRACE.zip](https://github.com/johnno1962/SwiftTrace/files/8546043/STRACE.zip)
Let me know If you have any further problems.

**Comment by tikimcfee** [comment]
I cannot thank you enough! With your changes here, I am able to trace out the class with pretty much exactly the fidelity I was hoping for and expecting, and it's working perfectly.

I've also opened up a tiny pull request at https://github.com/johnno1962/SwiftTrace/pull/40 to add on a small piece that is helping me use this patch. It turns out, there's some strange argument value in my function which is reporting as a string value, but crashes out in some .utf8 flows.

```
#0	0x00000001d20d37a0 in _StringObject.getSharedUTF8Start() ()
#1	0x00000001d20d37d0 in _StringObject.sharedUTF8.getter ()
#2	0x00000001d20cba14 in _StringGuts.append(_:) ()
#3	0x00000001d205bb2c in Character.write<τ_0_0>(to:) ()
#4	0x00000001d1efcc4c in DefaultStringInterpolation.appendInterpolation<τ_0_0>(_:) ()
#5	0x0000000104da4914 in static SwiftTrace.Decorated.describe(_:type:out:) at /Users/lugos/Library/Developer/Xcode/DerivedData/LookAtThat_AppKit-cknqatlzjmsdpwghvnspbgummawg/SourcePackages/checkouts/SwiftTrace/SwiftTrace/SwiftArgs.swift:636
#6	0x0000000104d9b6b8 in static SwiftTrace.Decorated.handleArg(invocation:isReturn:type:) at /Users/lugos/Library/Developer/Xcode/DerivedData/LookAtThat_AppKit-cknqatlzjmsdpwghvnspbgummawg/SourcePackages/checkouts/SwiftTrace/SwiftTrace/SwiftArgs.swift:600
#7	0x0000000104d9f8e0 in SwiftTrace.Decorated.swiftDecorate(signature:invocation:parser:) at /Users/lugos/Library/Developer/Xcode/DerivedData/LookAtThat_AppKit-cknqatlzjmsdpwghvnspbgummawg/SourcePackages/checkouts/SwiftTrace/SwiftTrace/SwiftArgs.swift:378
```

That one is super low priority since I have this easy workaround, but reporting it for ya nonetheless.

Again, thank you so much for this change!
