### ISSUE TITLE
ITMS-90338: Non-public API usage

### ISSUE THREAD

**Issue by softAlexs** [johnno1962/SwiftTrace#45]
I encountered Non-public API usage when I packaged and submitted to the App Store for review

ITMS-90338: Non-public API usage - The app references non-public symbols in Frameworks/SwiftTrace.framework/SwiftTrace: _dyld_dynamic_interpose. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at

**Comment by johnno1962** [comment]
Are you sure you are meaning to include SwiftTrace in your app? The strange thing is, SwiftTrace no longer contains a reference to dyld_dynamic_interpose in the active source code.
