### ISSUE TITLE
When tracking related classes of Foundation, such as NSURL and NSString, crashes occur. Can you help locate the issue?

### ISSUE THREAD

**Issue by amjunliang** [johnno1962/SwiftTrace#47]
[SwiftTrace traceWithAClass:NSString.class];
![image](https://github.com/johnno1962/SwiftTrace/assets/19588302/29644edd-3b9e-4f3f-868b-459a85be1e94)

[SwiftTrace traceWithAClass:NSURL.class];
![image](https://github.com/johnno1962/SwiftTrace/assets/19588302/46ff8b08-14c3-488e-957f-31c4ec97e7ab)

**Comment by johnno1962** [comment]
I don't think tracing system classes as fundamental as NSString and NSURL is likely to work.

**Comment by amjunliang** [comment]
Is there a way to avoid these crashes? For example, can we skip execution instead of crashing when such situations occur? Another question: which classes are currently confirmed to be supported by SwiftTrace for tracing to prevent misuse and avoid the aforementioned issues?

**Comment by johnno1962** [comment]
You can avoid these crashes by not trying to trace NSString or NSURL or other system classes individually. You should probably stick to tracing your own classes.
