### ISSUE TITLE
Crash using ADTECH Mobile SDK framework

### ISSUE THREAD

**Issue by ghost** [johnno1962/SwiftTrace#6]
Enabling tracing of the current bundle leads to this crash at launch for my project.
```
2017-03-15 16:12:33.374393 NZZ[1927:1350267] *** Terminating app due to uncaught exception 'Invalid Build Detected', reason: 'Unable to find ADTECHMobileAnalyticsSDK.bundle. Make sure it is added to your resources!'
*** First throw call stack:
(0x1818151b8 0x18024c55c 0x181815100 0x1005a6050 0x1005a61ec 0x1005a6688 0x1005a6120 0x1005a6960 0x18024d440 0x18024d6ac 0x180254c54 0x18025f298 0x1005a981c 0x18024d440 0x18024d6ac 0x180254c54 0x18025f298 0x101122820 0x101121e0c 0x10112096c 0x101120990 0x10048c1b0 0x10048b98c 0x10048ba10 0x10007d8ec 0x18773c6a4 0x18794ca98 0x187952808 0x187967104 0x18794f7ec 0x1833eb92c 0x1833eb798 0x1833ebb40 0x1817c2b5c 0x1817c24a4 0x1817c00a4 0x1816ee2b8 0x1877357b0 0x187730534 0x10007add0 0x1806d15b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

Without SwiftTrace it works and the bundle is added to the resources. When I remove the bundle I get another error. The problem seems to be that due to SwiftTrace somehow classes are instantiated which throw an NSException in ObjC.

I debugged this and found the following:

- The crash happens for a specific objc class from the framework in `open class func trace( _ aClass: AnyClass )` after the call `traceObjcClass(object_getClass( aClass ), which: "+")`
- Excluding the class using the exclusion pattern had no effect, although I checked in the debugger that the exclusion works.
- The exception is not thrown in the method `traceObjcClass(object_getClass( aClass ), which: "+")`, but immediately after returning and advancing one step.
- I can work around this when I add an early return in `open class func trace( _ aClass: AnyClass )` for this class.
- As can be seen in the following screenshot an exception is thrown after some initializers are called. This happens after returning from the method `traceObjcClass(object_getClass( aClass ), which: "+")` and advancing one step

<img width="1655" alt="screen shot 2017-03-15 at 16 23 39" src="https://cloud.githubusercontent.com/assets/926598/23956242/72480f02-099c-11e7-896c-08cc4da50a6d.png">

Do you need any further information or can I try something to fix this?

**Comment by johnno1962** [comment]
Have you tried adding an exception breakpoint to capture where the exception is being thrown from?

**Comment by ghost** [comment]
I did, you can see the state in the screenshot. It is thrown somewhere in the framework after an initializer is called.

**Comment by johnno1962** [comment]
Unless you can send me an example project I’m not sure how much help I can be. If you’re only interested in Swift tracing try commenting out the Objective-C side of things particularly the swizzling of “initialize”. https://github.com/johnno1962/SwiftTrace/blob/master/SwiftTrace/SwiftTrace.swift#L266
