### ISSUE TITLE
Example on usage from Objective-C?

### ISSUE THREAD

**Issue by aaronash** [johnno1962/SwiftTrace#8]
I'm likely just an idiot, but I can't seem to get the bridging headers stuff working correctly so I can use this from an Objective-C project. Is there something non-obvious here I might've missed?

Has anyone gotten this setup from Objective-C and wouldn't mind sharing an example project?

Thanks!

**Comment by johnno1962** [comment]
You probably want https://github.com/johnno1962/Xtrace for Objective-C
