### ISSUE TITLE
Should not the context register be saved as well?

### ISSUE THREAD

**Issue by flockoffiles** [johnno1962/SwiftTrace#9]
I was wondering whether r13 (the call context register) be saved as well (inside the assembly code)?
See: https://reverseengineering.stackexchange.com/questions/15725/calling-swift-4-methods-from-c
And: https://github.com/apple/swift/blob/master/docs/ABIStabilityManifesto.md#calling-convention

**Comment by johnno1962** [comment]
Thanks for this, you may be right. Looks like this was something added in Swift 4.

**Comment by flockoffiles** [comment]
By the way, thanks so much for the awesome component! I was trying to understand Swift vtables by just reading their docs, but having a live example is a life saver!

**Comment by johnno1962** [comment]
I’ve just pushed an update which should resolve this. %r13 is used for self and %rax used for structs
